package Dato;
// Generated 18 ene. 2020 17:10:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caja generated by hbm2java
 */
public class Caja  implements java.io.Serializable {


     private Integer id;
     private int monto1;
     private int monto5;
     private Date fechaAbierto;
     private boolean corte;
     private Date fechaCorte;
     private String nota;
     private boolean status;
     private Set devolucions = new HashSet(0);
     private Set gastos = new HashSet(0);

    public Caja() {
    }

	
    public Caja(int monto1, int monto5, Date fechaAbierto, boolean corte, boolean status) {
        this.monto1 = monto1;
        this.monto5 = monto5;
        this.fechaAbierto = fechaAbierto;
        this.corte = corte;
        this.status = status;
    }
    public Caja(int monto1, int monto5, Date fechaAbierto, boolean corte, Date fechaCorte, String nota, boolean status, Set devolucions, Set gastos) {
       this.monto1 = monto1;
       this.monto5 = monto5;
       this.fechaAbierto = fechaAbierto;
       this.corte = corte;
       this.fechaCorte = fechaCorte;
       this.nota = nota;
       this.status = status;
       this.devolucions = devolucions;
       this.gastos = gastos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMonto1() {
        return this.monto1;
    }
    
    public void setMonto1(int monto1) {
        this.monto1 = monto1;
    }
    public int getMonto5() {
        return this.monto5;
    }
    
    public void setMonto5(int monto5) {
        this.monto5 = monto5;
    }
    public Date getFechaAbierto() {
        return this.fechaAbierto;
    }
    
    public void setFechaAbierto(Date fechaAbierto) {
        this.fechaAbierto = fechaAbierto;
    }
    public boolean isCorte() {
        return this.corte;
    }
    
    public void setCorte(boolean corte) {
        this.corte = corte;
    }
    public Date getFechaCorte() {
        return this.fechaCorte;
    }
    
    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set devolucions) {
        this.devolucions = devolucions;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }
    
    
    public String contentCaja() {
        return "Monto1: " + this.monto1 +
       "monto5: " + this.monto5 +
       "fechaAbierto: " + this.fechaAbierto +
       "corte: " + this.corte +
       "fechaCorte: " + this.fechaCorte +
       "nota: " + this.nota +
       "status: " + this.status +
       "devolucions: " + this.devolucions +
       "gastos: " + this.gastos + "";
    }



}


