package Dato;
// Generated 18 ene. 2020 17:10:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer id;
     private Caja caja;
     private Tipogasto tipogasto;
     private Date fecha;
     private double gasto;
     private String descripcion;
     private boolean status;

    public Gasto() {
    }

	
    public Gasto(Caja caja, Tipogasto tipogasto, Date fecha, double gasto, boolean status) {
        this.caja = caja;
        this.tipogasto = tipogasto;
        this.fecha = fecha;
        this.gasto = gasto;
        this.status = status;
    }
    public Gasto(Caja caja, Tipogasto tipogasto, Date fecha, double gasto, String descripcion, boolean status) {
       this.caja = caja;
       this.tipogasto = tipogasto;
       this.fecha = fecha;
       this.gasto = gasto;
       this.descripcion = descripcion;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Caja getCaja() {
        return this.caja;
    }
    
    public void setCaja(Caja caja) {
        this.caja = caja;
    }
    public Tipogasto getTipogasto() {
        return this.tipogasto;
    }
    
    public void setTipogasto(Tipogasto tipogasto) {
        this.tipogasto = tipogasto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getGasto() {
        return this.gasto;
    }
    
    public void setGasto(double gasto) {
        this.gasto = gasto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


