package Dato;
// Generated 18 ene. 2020 17:10:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipogasto generated by hbm2java
 */
public class Tipogasto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private boolean status;
     private Set gastos = new HashSet(0);

    public Tipogasto() {
    }

	
    public Tipogasto(String nombre, boolean status) {
        this.nombre = nombre;
        this.status = status;
    }
    public Tipogasto(String nombre, String descripcion, boolean status, Set gastos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.status = status;
       this.gastos = gastos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }




}


